name: Fetch News (hourly)

on:
  schedule:
    - cron: '0 * * * *'   # every hour at minute 0
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Build data
        run: npm run build

      - name: Commit & push
        run: |
          git config user.name "news-bot"
          git config user.email "actions@users.noreply.github.com"
          git add data/news.json package-lock.json || true
          git commit -m "chore: update news data [skip ci]" || echo "no changes"
          git push
